-- NOT APPLIED — left here only as a note for whoever next opens
-- schema.prisma for this area, not as a migration to run.
--
-- Chunk D (Portal accounts) needs a durable "exactly one default site" flag
-- on portal_account_sites, but this chunk's brief forbids editing
-- schema.prisma (shared with concurrent chunks) and the sandbox refuses any
-- direct DB schema change from this agent. So chunk D does NOT add a column
-- here: it stores the default marker in the existing, portal-unused
-- PortalAccountSite.region text column instead (see DEFAULT_SITE_MARKER in
-- src/lib/portal/accounts.ts). That is a documented stand-in, not a design
-- choice worth keeping — when schema.prisma is next open for this area,
-- add a real `isDefault Boolean @default(false)` field to PortalAccountSite,
-- backfill it from `region = 'portal_default'`, and delete this file along
-- with the region-based marker code it replaces.
